# Definition file sample

params = ["who", "speech"]
fields = ["line_number","speaker", "text_entry"]

[esconfig.default]
url = "http://localhost:9200"
username = ""
password = ""

[[search]]
name = "alpha"
es = "default"
index = "shakespeare"
query = """
{
  "query": {
    "bool": {
      "should": [
        {
          "match": {
            "speaker": "{{who}}"
          }
        },
        {
          "match": {
            "text_entry": "{{speech}}"
          }
        }
      ]
    }
  }
}
"""

[[search]]
name = "beta"
es = "default"
index = "shakespeare"
query = """
{
  "query": {
    "bool": {
      "should": [
        {
          "match": {
            "speaker": {
              "query": "{{who}}"
            }
          }
        },
        {
          "match": {
            "text_entry": {
              "query": "{{speech}}",
              "boost": 0.5
            }
          }
        }
      ]
    }
  }
}
"""
