# Definition file sample

params = ["keyword"]
fields = ["speaker", "text_entry"]

[esconfig.default]
url = "http://localhost:9200"
username = ""
password = ""

[[search]]
name = "alpha"
es = "default"
index = "shakespeare"
query = """
{
  "query": {
    "match": {
      "text_entry": "{{keyword}}"
    }
  }
}
"""

[[search]]
name = "beta"
es = "default"
index = "shakespeare"
query = """
{
  "query": {
    "bool": {
      "must": [
        {
          "match": {
            "text_entry": "{{keyword}}"
          }
        }
      ],
      "should": [
        {
          "match": {
            "speaker": "{{keyword}}"
          }
        }
      ]
    }
  }
}
"""
